export const authConstants = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};


export const hamburgerConstants = { 

    PROFILE: '/PROFILE',
    HOME: '/HOME',
}

export const calendarConstants = {

    STUDENT_CALENDAR_FIRESTORE_FAILURE: 'CALENDAR_FIRESTORE_FAILURE',
    GET_SUBJECT_FAILURE: 'GET_SUBJECT_FAILURE',

    UPDATE_STUDENT_CALENDAR_SUCCESS: 'UPDATE_STUDENT_CALENDAR',
    UPDATE_STUDENT_CALENDAR_FAILURE: 'UPDATE_FAILURE',
    
    UPDATE_SUBJECT_CONSULTATIONS_SUCCESS: "UPDATE_SUBJECT_CONSULTATIONS_SUCCESS",
    UPDATE_SUBJECT_CONSULTATIONS_FAILURE: "UPDATE_SUBJECT_CONSULTATIONS_FAILURE",


}


